/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Order {
  'id' : string,
  'rankName' : string,
  'status' : string,
  'owner' : Principal,
  'minecraftUsername' : string,
  'timestamp' : bigint,
  'rankId' : string,
  'price' : number,
}
export interface Rank {
  'id' : string,
  'name' : string,
  'color' : string,
  'tier' : bigint,
  'description' : string,
  'isActive' : boolean,
  'perks' : Array<string>,
  'price' : number,
}
export interface UserProfile { 'minecraftUsername' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createRank' : ActorMethod<[Rank], undefined>,
  'deleteRank' : ActorMethod<[string], undefined>,
  'getActiveRanks' : ActorMethod<[], Array<Rank>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getOrder' : ActorMethod<[string], [] | [Order]>,
  'getOrdersByUsername' : ActorMethod<[string], Array<Order>>,
  'getRank' : ActorMethod<[string], [] | [Rank]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[string, string], string>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateOrderStatus' : ActorMethod<[string, string], undefined>,
  'updateRank' : ActorMethod<[Rank], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];