/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Rank = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'color' : IDL.Text,
  'tier' : IDL.Nat,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'perks' : IDL.Vec(IDL.Text),
  'price' : IDL.Float64,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'rankName' : IDL.Text,
  'status' : IDL.Text,
  'owner' : IDL.Principal,
  'minecraftUsername' : IDL.Text,
  'timestamp' : IDL.Int,
  'rankId' : IDL.Text,
  'price' : IDL.Float64,
});
export const UserProfile = IDL.Record({ 'minecraftUsername' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createRank' : IDL.Func([Rank], [], []),
  'deleteRank' : IDL.Func([IDL.Text], [], []),
  'getActiveRanks' : IDL.Func([], [IDL.Vec(Rank)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
  'getOrdersByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
  'getRank' : IDL.Func([IDL.Text], [IDL.Opt(Rank)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'updateRank' : IDL.Func([Rank], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Rank = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'color' : IDL.Text,
    'tier' : IDL.Nat,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'perks' : IDL.Vec(IDL.Text),
    'price' : IDL.Float64,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'rankName' : IDL.Text,
    'status' : IDL.Text,
    'owner' : IDL.Principal,
    'minecraftUsername' : IDL.Text,
    'timestamp' : IDL.Int,
    'rankId' : IDL.Text,
    'price' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'minecraftUsername' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createRank' : IDL.Func([Rank], [], []),
    'deleteRank' : IDL.Func([IDL.Text], [], []),
    'getActiveRanks' : IDL.Func([], [IDL.Vec(Rank)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getOrder' : IDL.Func([IDL.Text], [IDL.Opt(Order)], ['query']),
    'getOrdersByUsername' : IDL.Func([IDL.Text], [IDL.Vec(Order)], ['query']),
    'getRank' : IDL.Func([IDL.Text], [IDL.Opt(Rank)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'updateRank' : IDL.Func([Rank], [], []),
  });
};

export const init = ({ IDL }) => { return []; };